default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['victoroliveira59'] %>
  password: <%= ENV['354637'] %>
  host: localhost

development:
  <<: *default
  database: meu_projeto_development

test:
  <<: *default
  database: meu_projeto_test

production:
  <<: *default
  database: meu_projeto_production
